name: Send message to Discord

on:
  workflow_dispatch:

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message with embed
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST -d '{
              "username": "BersksAuto",
              "embeds": [{
                "title": "🎮 Novo Jogador Detectado",
                "description": "**Nick:** BersksAuto\n**Players:** 5\n**Link:** [Clique para entrar](https://hkdk.events/w83hamue5mkffw)",
                "color": 5814783,
                "footer": {
                  "text": "Sistema Automático - Bersks Method"
                }
              }]
            }' $WEBHOOK_URL
